version: '3.9'


services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TicketAirport
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"



  ticket_service:
    restart: on-failure
    container_name: ticket_service
    build: ./ticket_service/
    ports:
      - "8000:80"
    depends_on:
      - database

  statistics_service:
    restart: on-failure
    container_name: statistics_service
    build: ./statistics_service/
    ports:
      - "8001:80"
    depends_on:
      - database
